name: "Production: Tag Release and Deploy"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The version tag number to apply to release (vX.Y.Z)
        required: true
        type: string
      release_name:
        description: The name of the release to apply, generally this is a description of what is included.
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACTION_PAT }}
          custom_tag: ${{ inputs.tag }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GH_ACTION_PAT }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }} - ${{ inputs.release_name }}
          body: ${{ steps.tag_version.outputs.changelog }}

